dist: xenial
language: python
python:
  - "3.6"
cache: pip

before_install:
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3=3.7.15.1-1~travis1
install: 
  - pip install -r requirements.txt

script:
  - python manage.py test
  - black --check --verbose api/*.py urlShortenerAPI/*py *.py

branches:
  only:
  - master