dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip

install:
  - pip install -r requirements-build.txt

script:
  - coverage run --source='.' manage.py test
  - black --check --verbose api/*.py urlShortenerAPI/*py *.py
after_success:
  - codecov

deploy:
  provider: gae
  keyfile: url-shortener-79965195076f.json
  project: url-shortener-jlb
  on:
    branch: master
    python: "3.7"
    condition: $TRAVIS_EVENT_TYPE != cron

before_install:
- openssl aes-256-cbc -K $encrypted_e40c4c0b041c_key -iv $encrypted_e40c4c0b041c_iv
  -in url-shortener-79965195076f.json.enc -out url-shortener-79965195076f.json -d
